// Curated problem list. Each question: [leetcodeNumber, title, difficulty (E/M/H), priority (M=Must, S=Should, X=Stretch), note]
const T=[
{"t":"Arrays & Hashing","w":"Week 1","c":"Hashmap/set patterns, prefix sums, Kadane, in-place array tricks","q":[
[217,"Contains Duplicate","E","M","Set membership check · 19 cos."],
[242,"Valid Anagram","E","M","Frequency count / array of 26 · 39 cos."],
[49,"Group Anagrams","M","M","Sorted string or count-tuple as hash key · 79 cos."],
[347,"Top K Frequent Elements","M","M","Freq map + bucket sort or heap · 51 cos."],
[238,"Product of Array Except Self","M","M","Prefix and suffix products, no division · 35 cos."],
[36,"Valid Sudoku","M","S","Sets per row / column / 3x3 box · 24 cos."],
[128,"Longest Consecutive Sequence","M","M","Set + only start counting at sequence start · 40 cos."],
[560,"Subarray Sum Equals K","M","M","Prefix sum + hashmap of seen sums · 43 cos."],
[525,"Contiguous Array","M","S","Prefix sum with 0 mapped to -1 · 14 cos."],
[303,"Range Sum Query - Immutable","E","S","Prefix sum array"],
[53,"Maximum Subarray","M","M","Kadane's algorithm · 59 cos."],
[169,"Majority Element","E","S","Boyer-Moore voting · 24 cos."],
[189,"Rotate Array","M","S","Reverse whole, then two parts · 27 cos."],
[75,"Sort Colors","M","M","Dutch national flag, 3 pointers · 37 cos."],
[41,"First Missing Positive","H","X","Use array indices as hash (cyclic placement) · 30 cos."],
[88,"Merge Sorted Array","E","S","Fill from the back · 34 cos."],
[118,"Pascal's Triangle","E","S","Build row from previous · 14 cos."],
[219,"Contains Duplicate II","E","S","Hashmap of last index · 14 cos."],
[229,"Majority Element II","M","S","Boyer-Moore with 2 candidates · 10 cos."],
[442,"Find All Duplicates in an Array","M","S","Mark visited via sign flip · 10 cos."],
[454,"4Sum II","M","S","Two-sum split in two halves"],
[485,"Max Consecutive Ones","E","S","Running count · 13 cos."],
[665,"Non-decreasing Array","M","S","Greedy single fix"],
[724,"Find Pivot Index","E","S","Prefix sum balance · 15 cos."],
[974,"Subarray Sums Divisible by K","M","S","Prefix sum remainders · 10 cos."],
[80,"Remove Duplicates from Sorted Array II","M","S","Write pointer, allow 2"],
[918,"Maximum Sum Circular Subarray","M","S","Kadane + total minus min · 12 cos."],
[1,"Two Sum","E","M","Hash complement lookup · 115 cos."],
[15,"3Sum","M","M","Sort + two pointers, skip dups · 49 cos."],
[18,"4Sum","M","S","k-sum generalisation · 18 cos."],
[31,"Next Permutation","M","M","Find pivot, swap, reverse suffix · 31 cos."],
[26,"Remove Duplicates from Sorted Array","E","S","Write pointer · 23 cos."],
[27,"Remove Element","E","S","Write pointer · 11 cos."],
[523,"Continuous Subarray Sum","M","S","Prefix sum mod k + first index · 10 cos."],
[1010,"Pairs of Songs With Total Durations Divisible by 60","M","S","Remainder counts"]
]},
{"t":"Strings","w":"Week 2","c":"Frequency counting, two pointers on strings, arithmetic on strings","q":[
[28,"Find the Index of the First Occurrence in a String","E","S","Brute force, then learn KMP idea · 16 cos."],
[151,"Reverse Words in a String","M","S","Split/reverse or in-place two pointers · 26 cos."],
[205,"Isomorphic Strings","E","S","Two-way character mapping · 15 cos."],
[387,"First Unique Character in a String","E","S","Frequency count · 23 cos."],
[5,"Longest Palindromic Substring","M","M","Expand around center · 74 cos."],
[647,"Palindromic Substrings","M","S","Expand around center, count all · 25 cos."],
[344,"Reverse String","E","S","Two pointers swap · 16 cos."],
[345,"Reverse Vowels of a String","E","S","Two pointers on vowels · 13 cos."],
[383,"Ransom Note","E","S","Frequency count · 13 cos."],
[392,"Is Subsequence","E","S","Two pointers · 15 cos."],
[409,"Longest Palindrome","E","S","Count pairs of chars"],
[415,"Add Strings","E","S","Digit add with carry · 15 cos."],
[43,"Multiply Strings","M","S","Grade-school multiplication · 17 cos."],
[67,"Add Binary","E","S","Bitwise add with carry · 16 cos."],
[8,"String to Integer (atoi)","M","S","State handling + overflow · 21 cos."],
[12,"Integer to Roman","M","S","Greedy over value table · 30 cos."],
[171,"Excel Sheet Column Number","E","S","Base-26 conversion"],
[168,"Excel Sheet Column Title","E","S","Base-26 with offset"],
[459,"Repeated Substring Pattern","E","S","(s+s)[1:-1] contains s"],
[696,"Count Binary Substrings","E","S","Group lengths of 0s/1s · 14 cos."],
[6,"Zigzag Conversion","M","S","Row simulation · 17 cos."],
[38,"Count and Say","M","S","Run-length iteration · 12 cos."],
[165,"Compare Version Numbers","M","S","Split and compare ints · 10 cos."],
[443,"String Compression","M","M","Read/write pointers · 37 cos."],
[14,"Longest Common Prefix","E","M","Vertical scan / sort ends · 52 cos."],
[271,"Encode and Decode Strings","M","M","Length-prefix encoding"],
[68,"Text Justification","H","X","Greedy line packing · 35 cos."],
[273,"Integer to English Words","H","X","Chunk by thousands · 19 cos."],
[10,"Regular Expression Matching","H","X","2D DP on pattern · 22 cos."],
[44,"Wildcard Matching","H","X","2D DP / greedy two pointers · 16 cos."]
]},
{"t":"Two Pointers","w":"Week 2","c":"Converging pointers, slow/fast pointers, sort + pointers","q":[
[125,"Valid Palindrome","E","M","Left/right pointers, skip non-alphanumerics · 37 cos."],
[167,"Two Sum II - Input Array Is Sorted","M","M","Converging pointers on sorted array · 15 cos."],
[42,"Trapping Rain Water","H","M","Two pointers with leftMax / rightMax · 72 cos."],
[283,"Move Zeroes","E","M","Slow/fast write pointer · 39 cos."],
[680,"Valid Palindrome II","E","S","Palindrome with one skip allowed · 16 cos."],
[977,"Squares of a Sorted Array","E","S","Fill result from the back with two pointers · 17 cos."],
[633,"Sum of Square Numbers","M","S","Two pointers 0..sqrt(c)"],
[653,"Two Sum IV - Input is a BST","E","S","Inorder + two pointers"],
[349,"Intersection of Two Arrays","E","S","Set intersection · 14 cos."],
[350,"Intersection of Two Arrays II","E","S","Counter / sorted pointers"],
[844,"Backspace String Compare","E","S","Two pointers from the end · 13 cos."],
[925,"Long Pressed Name","E","S","Two pointers match"],
[581,"Shortest Unsorted Continuous Subarray","M","S","Find min/max out of place"],
[611,"Valid Triangle Number","M","S","Sort + two pointers"],
[923,"3Sum With Multiplicity","M","S","Sort + pointers with counts"],
[1498,"Number of Subsequences That Satisfy the Given Sum Condition","M","S","Sort + powers of 2"],
[881,"Boats to Save People","M","M","Sort + pair heaviest with lightest · 12 cos."],
[1679,"Max Number of K-Sum Pairs","M","M","Sort + two pointers"],
[475,"Heaters","M","S","Sort + nearest heater · 12 cos."],
[1574,"Shortest Subarray to be Removed to Make Array Sorted","M","S","Prefix + suffix merge pointers"],
[1963,"Minimum Number of Swaps to Make the String Balanced","M","S","Count unmatched brackets · 13 cos."],
[2161,"Partition Array According to Given Pivot","M","S","Three-bucket partition"],
[11,"Container With Most Water","M","M","Shrink the shorter side · 54 cos."],
[16,"3Sum Closest","M","S","Sort + two pointers · 12 cos."],
[1099,"Two Sum Less Than K","E","S","Sort + two pointers"]
]},
{"t":"Sliding Window","w":"Week 3","c":"Fixed vs variable window, atMost(k) trick, monotonic deque","q":[
[121,"Best Time to Buy and Sell Stock","E","M","Track min price so far · 82 cos."],
[3,"Longest Substring Without Repeating Characters","M","M","Variable window + set/map · 97 cos."],
[424,"Longest Repeating Character Replacement","M","M","Window valid if len - maxFreq <= k · 21 cos."],
[567,"Permutation in String","M","M","Fixed window + frequency match · 16 cos."],
[76,"Minimum Window Substring","H","M","Variable window, need/have counters · 36 cos."],
[239,"Sliding Window Maximum","H","M","Monotonic deque · 47 cos."],
[643,"Maximum Average Subarray I","E","S","Fixed-size window sum · 10 cos."],
[209,"Minimum Size Subarray Sum","M","M","Shrinkable window on positive numbers · 17 cos."],
[1004,"Max Consecutive Ones III","M","S","Window with at most k zeros · 20 cos."],
[438,"Find All Anagrams in a String","M","S","Fixed window + frequency match · 14 cos."],
[713,"Subarray Product Less Than K","M","S","Shrinking window on product · 21 cos."],
[904,"Fruit Into Baskets","M","M","Window with at most 2 distinct · 13 cos."],
[930,"Binary Subarrays With Sum","M","S","Prefix sum / atMost trick"],
[992,"Subarrays with K Different Integers","H","X","atMost(k) - atMost(k-1) · 17 cos."],
[1493,"Longest Subarray of 1's After Deleting One Element","M","S","Window with one zero"],
[1052,"Grumpy Bookstore Owner","M","S","Fixed window bonus"],
[1423,"Maximum Points You Can Obtain from Cards","M","S","Min window of remaining · 11 cos."],
[1695,"Maximum Erasure Value","M","S","Unique window sum"],
[480,"Sliding Window Median","H","X","Two heaps with removal"],
[1248,"Count Number of Nice Subarrays","M","S","atMost(k) trick"],
[1358,"Number of Substrings Containing All Three Characters","M","S","Window + count of results"],
[2461,"Maximum Sum of Distinct Subarrays With Length K","M","S","Fixed window + set"],
[1838,"Frequency of the Most Frequent Element","M","S","Sort + window cost · 11 cos."],
[340,"Longest Substring with At Most K Distinct Characters","M","M","Window + freq map · 12 cos."],
[1438,"Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit","M","S","Two monotonic deques · 14 cos."]
]},
{"t":"Stack & Monotonic Stack","w":"Week 4","c":"Bracket matching, next-greater pattern, histogram, expression parsing","q":[
[20,"Valid Parentheses","E","M","Stack of open brackets · 99 cos."],
[155,"Min Stack","M","M","Stack storing (value, current min) · 37 cos."],
[150,"Evaluate Reverse Polish Notation","M","S","Operand stack · 18 cos."],
[739,"Daily Temperatures","M","M","Monotonic decreasing stack of indices · 28 cos."],
[496,"Next Greater Element I","E","S","Monotonic stack + hashmap · 16 cos."],
[503,"Next Greater Element II","M","S","Monotonic stack over circular array (2x pass) · 17 cos."],
[84,"Largest Rectangle in Histogram","H","M","Monotonic increasing stack · 29 cos."],
[853,"Car Fleet","M","S","Sort by position, compare arrival times · 11 cos."],
[394,"Decode String","M","M","Stack of (count, string) · 40 cos."],
[901,"Online Stock Span","M","S","Monotonic stack with counts"],
[227,"Basic Calculator II","M","S","Stack with last-operator handling · 27 cos."],
[735,"Asteroid Collision","M","M","Stack simulation · 35 cos."],
[71,"Simplify Path","M","S","Stack of directory names · 22 cos."],
[232,"Implement Queue using Stacks","E","S","Two stacks (amortised O(1)) · 12 cos."],
[225,"Implement Stack using Queues","E","S","One queue rotation"],
[1047,"Remove All Adjacent Duplicates In String","E","S","Stack pop on match · 14 cos."],
[921,"Minimum Add to Make Parentheses Valid","M","S","Balance counter"],
[1249,"Minimum Remove to Make Valid Parentheses","M","M","Stack of indices · 11 cos."],
[32,"Longest Valid Parentheses","H","S","Stack of indices / DP · 26 cos."],
[316,"Remove Duplicate Letters","M","S","Monotonic stack + last index · 13 cos."],
[402,"Remove K Digits","M","M","Monotonic increasing stack · 21 cos."],
[456,"132 Pattern","M","S","Monotonic stack from right"],
[907,"Sum of Subarray Minimums","M","S","Monotonic stack contribution · 15 cos."],
[85,"Maximal Rectangle","H","X","Histogram per row · 14 cos."],
[946,"Validate Stack Sequences","M","S","Simulate push/pop"],
[224,"Basic Calculator","H","S","Stack with signs · 22 cos."],
[2104,"Sum of Subarray Ranges","M","S","Monotonic stack max - min"],
[1209,"Remove All Adjacent Duplicates in String II","M","S","Stack of (char,count) · 18 cos."],
[341,"Flatten Nested List Iterator","M","S","Stack of iterators · 18 cos."],
[636,"Exclusive Time of Functions","M","S","Stack of call frames · 12 cos."],
[769,"Max Chunks To Make Sorted","M","S","Running max == index"]
]},
{"t":"Binary Search","w":"Week 4","c":"Lower/upper bound, rotated arrays, binary search on answer","q":[
[704,"Binary Search","E","M","Template: lo, hi, mid · 13 cos."],
[69,"Sqrt(x)","E","S","Binary search on answer · 17 cos."],
[74,"Search a 2D Matrix","M","M","Treat matrix as flattened sorted array · 20 cos."],
[153,"Find Minimum in Rotated Sorted Array","M","M","Compare mid with right end · 17 cos."],
[162,"Find Peak Element","M","S","Move toward the rising slope · 31 cos."],
[875,"Koko Eating Bananas","M","M","Binary search on answer space · 43 cos."],
[1011,"Capacity To Ship Packages Within D Days","M","M","Binary search on answer + greedy check · 19 cos."],
[981,"Time Based Key-Value Store","M","S","Hashmap of sorted lists + bisect · 32 cos."],
[410,"Split Array Largest Sum","H","S","Binary search on answer (min-max pattern) · 21 cos."],
[367,"Valid Perfect Square","E","S","Binary search on answer"],
[744,"Find Smallest Letter Greater Than Target","E","S","Upper bound"],
[278,"First Bad Version","E","M","Lower bound on predicate"],
[852,"Peak Index in a Mountain Array","M","S","Slope-based search"],
[1095,"Find in Mountain Array","H","X","Peak + two searches"],
[540,"Single Element in a Sorted Array","M","S","Pair index parity · 18 cos."],
[81,"Search in Rotated Sorted Array II","M","S","Handle duplicates · 10 cos."],
[154,"Find Minimum in Rotated Sorted Array II","H","X","Shrink on equal"],
[240,"Search a 2D Matrix II","M","M","Staircase from top-right · 14 cos."],
[1760,"Minimum Limit of Balls in a Bag","M","S","Binary search on answer"],
[1482,"Minimum Number of Days to Make m Bouquets","M","S","Binary search on answer"],
[2187,"Minimum Time to Complete Trips","M","S","Binary search on time"],
[1283,"Find the Smallest Divisor Given a Threshold","M","S","Binary search on answer · 12 cos."],
[658,"Find K Closest Elements","M","S","Binary search window start · 19 cos."],
[1539,"Kth Missing Positive Number","E","S","Binary search on missing count"],
[719,"Find K-th Smallest Pair Distance","H","X","BS on distance + window"],
[2300,"Successful Pairs of Spells and Potions","M","S","Sort + lower bound"],
[33,"Search in Rotated Sorted Array","M","M","Find the sorted half · 49 cos."],
[34,"Find First and Last Position of Element in Sorted Array","M","M","Lower / upper bound · 29 cos."],
[35,"Search Insert Position","E","S","Lower bound · 12 cos."],
[4,"Median of Two Sorted Arrays","H","M","Binary search on partition · 44 cos."],
[528,"Random Pick with Weight","M","S","Prefix sums + bisect · 24 cos."]
]},
{"t":"Linked List","w":"Week 5","c":"Reversal, fast/slow, dummy node, merge, hashmap + DLL (LRU)","q":[
[206,"Reverse Linked List","E","M","Iterative prev/curr; also recursive · 34 cos."],
[21,"Merge Two Sorted Lists","E","M","Dummy node + pointer merge · 37 cos."],
[141,"Linked List Cycle","E","M","Floyd's slow/fast · 23 cos."],
[142,"Linked List Cycle II","M","M","Floyd's, then reset to head · 11 cos."],
[876,"Middle of the Linked List","E","M","Slow/fast pointers · 13 cos."],
[19,"Remove Nth Node From End of List","M","M","Gap of n between two pointers · 17 cos."],
[143,"Reorder List","M","M","Find middle + reverse half + merge · 15 cos."],
[234,"Palindrome Linked List","E","S","Middle + reverse second half · 16 cos."],
[2,"Add Two Numbers","M","M","Digit-by-digit with carry · 36 cos."],
[160,"Intersection of Two Linked Lists","E","S","Pointer switching trick · 13 cos."],
[138,"Copy List with Random Pointer","M","S","Hashmap old->new, or interleave nodes · 21 cos."],
[92,"Reverse Linked List II","M","S","Reverse sublist in place · 16 cos."],
[25,"Reverse Nodes in k-Group","H","S","Group reversal with dummy head · 27 cos."],
[23,"Merge k Sorted Lists","H","M","Min-heap or divide & conquer · 49 cos."],
[148,"Sort List","M","S","Merge sort on linked list"],
[146,"LRU Cache","M","M","Hashmap + doubly linked list · 109 cos."],
[287,"Find the Duplicate Number","M","S","Floyd's cycle on index graph · 22 cos."],
[24,"Swap Nodes in Pairs","M","S","Pointer rewiring with dummy · 14 cos."],
[83,"Remove Duplicates from Sorted List","E","S","Skip equal nodes"],
[82,"Remove Duplicates from Sorted List II","M","S","Dummy + skip duplicates · 10 cos."],
[203,"Remove Linked List Elements","E","S","Dummy head"],
[61,"Rotate List","M","S","Make circular, cut at k"],
[86,"Partition List","M","S","Two dummy lists"],
[328,"Odd Even Linked List","M","S","Two pointer chains · 11 cos."],
[237,"Delete Node in a Linked List","M","S","Copy next value"],
[430,"Flatten a Multilevel Doubly Linked List","M","S","DFS with stack"],
[445,"Add Two Numbers II","M","S","Stack of digits"],
[2095,"Delete the Middle Node of a Linked List","M","S","Slow/fast"],
[2130,"Maximum Twin Sum of a Linked List","M","S","Reverse second half"]
]},
{"t":"Trees & BST","w":"Week 6","c":"DFS orders, BFS levels, LCA, return-value vs global recursion, BST property","q":[
[104,"Maximum Depth of Binary Tree","E","M","DFS recursion · 18 cos."],
[226,"Invert Binary Tree","E","M","Swap children recursively"],
[100,"Same Tree","E","M","Parallel DFS"],
[572,"Subtree of Another Tree","E","S","Same Tree inside DFS"],
[543,"Diameter of Binary Tree","E","M","Height with global max · 20 cos."],
[110,"Balanced Binary Tree","E","S","Height, return -1 if unbalanced"],
[101,"Symmetric Tree","E","S","Mirror DFS · 11 cos."],
[102,"Binary Tree Level Order Traversal","M","M","BFS with queue, level size · 14 cos."],
[199,"Binary Tree Right Side View","M","M","BFS last node per level · 15 cos."],
[103,"Binary Tree Zigzag Level Order Traversal","M","S","BFS + direction flag · 19 cos."],
[94,"Binary Tree Inorder Traversal","E","M","Recursive + iterative with stack"],
[236,"Lowest Common Ancestor of a Binary Tree","M","M","Post-order: return node if found · 22 cos."],
[112,"Path Sum","E","S","DFS with remaining sum"],
[113,"Path Sum II","M","S","DFS + backtracking path · 10 cos."],
[437,"Path Sum III","M","S","Prefix sum on tree paths · 10 cos."],
[124,"Binary Tree Maximum Path Sum","H","M","Post-order, ignore negative gains · 24 cos."],
[105,"Construct Binary Tree from Preorder and Inorder Traversal","M","M","Root from preorder, split by inorder index · 10 cos."],
[297,"Serialize and Deserialize Binary Tree","H","S","Preorder with null markers · 22 cos."],
[114,"Flatten Binary Tree to Linked List","M","S","Reverse post-order / Morris-like"],
[1448,"Count Good Nodes in Binary Tree","M","S","DFS carrying max so far"],
[98,"Validate Binary Search Tree","M","M","DFS with (low, high) bounds · 19 cos."],
[230,"Kth Smallest Element in a BST","M","M","Inorder traversal · 12 cos."],
[235,"Lowest Common Ancestor of a Binary Search Tree","M","M","Use BST ordering · 10 cos."],
[700,"Search in a Binary Search Tree","E","S","Walk left/right"],
[701,"Insert into a Binary Search Tree","M","S","Recursive insert"],
[450,"Delete Node in a BST","M","S","Replace with inorder successor · 11 cos."],
[108,"Convert Sorted Array to Binary Search Tree","E","S","Mid as root, recurse"],
[173,"Binary Search Tree Iterator","M","S","Controlled inorder with stack"],
[144,"Binary Tree Preorder Traversal","E","M","Recursive + iterative"],
[145,"Binary Tree Postorder Traversal","E","S","Iterative with stack"],
[111,"Minimum Depth of Binary Tree","E","S","BFS first leaf"],
[222,"Count Complete Tree Nodes","E","S","Use perfect-subtree height"],
[257,"Binary Tree Paths","E","S","DFS path build"],
[404,"Sum of Left Leaves","E","S","DFS with side flag"],
[129,"Sum Root to Leaf Numbers","M","S","DFS carrying number"],
[987,"Vertical Order Traversal of a Binary Tree","H","X","Column/row sort · 14 cos."],
[863,"All Nodes Distance K in Binary Tree","M","S","Parent map + BFS · 18 cos."],
[652,"Find Duplicate Subtrees","M","X","Serialize subtrees"],
[669,"Trim a Binary Search Tree","M","S","Recursion by bounds"],
[538,"Convert BST to Greater Tree","M","S","Reverse inorder"],
[617,"Merge Two Binary Trees","E","S","Parallel DFS"],
[106,"Construct Binary Tree from Inorder and Postorder Traversal","M","S","Root from postorder end"],
[530,"Minimum Absolute Difference in BST","E","S","Inorder neighbours"],
[1008,"Construct Binary Search Tree from Preorder Traversal","M","S","Bounds recursion"],
[337,"House Robber III","M","S","DFS returning (rob, skip) · 12 cos."],
[116,"Populating Next Right Pointers in Each Node","M","S","Use next pointers level by level"],
[314,"Binary Tree Vertical Order Traversal","M","S","BFS with column index · 10 cos."],
[662,"Maximum Width of Binary Tree","M","S","BFS with heap-style indices"],
[99,"Recover Binary Search Tree","M","S","Inorder, find two swapped nodes"],
[2385,"Amount of Time for Binary Tree to Be Infected","M","S","Tree to graph + BFS · 13 cos."],
[1650,"Lowest Common Ancestor of a Binary Tree III","M","S","Two pointers like list intersection · 11 cos."]
]},
{"t":"Heap, Tries & Design","w":"Week 7","c":"Top-K, two-heap median, Trie, design problems (LRU/LFU/RandomizedSet)","q":[
[703,"Kth Largest Element in a Stream","E","M","Min-heap of size k"],
[1046,"Last Stone Weight","E","S","Max-heap simulation · 11 cos."],
[973,"K Closest Points to Origin","M","M","Max-heap of size k or quickselect · 15 cos."],
[215,"Kth Largest Element in an Array","M","M","Heap or quickselect · 41 cos."],
[621,"Task Scheduler","M","S","Max-heap/greedy on frequency · 23 cos."],
[355,"Design Twitter","M","S","Heap merge of k lists · 14 cos."],
[295,"Find Median from Data Stream","H","M","Two heaps (max-heap + min-heap) · 43 cos."],
[767,"Reorganize String","M","S","Max-heap by frequency · 19 cos."],
[378,"Kth Smallest Element in a Sorted Matrix","M","S","Min-heap or binary search · 11 cos."],
[208,"Implement Trie (Prefix Tree)","M","M","Node with children map + end flag · 21 cos."],
[211,"Design Add and Search Words Data Structure","M","S","Trie + DFS for wildcard · 13 cos."],
[212,"Word Search II","H","S","Trie + backtracking on grid · 19 cos."],
[648,"Replace Words","M","S","Shortest prefix lookup in Trie"],
[1268,"Search Suggestions System","M","S","Trie or sort + binary search · 18 cos."],
[380,"Insert Delete GetRandom O(1)","M","M","Array + hashmap swap-remove · 37 cos."],
[460,"LFU Cache","H","S","Freq buckets + LRU · 33 cos."],
[705,"Design HashSet","E","S","Bucket array"],
[706,"Design HashMap","E","S","Chaining · 11 cos."],
[622,"Design Circular Queue","M","S","Ring buffer · 22 cos."],
[641,"Design Circular Deque","M","S","Ring buffer both ends"],
[1472,"Design Browser History","M","S","Array with pointer · 12 cos."],
[1396,"Design Underground System","M","S","Two hashmaps"],
[421,"Maximum XOR of Two Numbers in an Array","M","S","Bitwise trie"],
[692,"Top K Frequent Words","M","M","Heap with tie-break · 21 cos."],
[451,"Sort Characters By Frequency","M","S","Freq + heap/bucket · 16 cos."],
[502,"IPO","H","X","Two heaps greedy"],
[1962,"Remove Stones to Minimize the Total","M","S","Max-heap"],
[253,"Meeting Rooms II","M","M","Min-heap of end times · 41 cos."],
[252,"Meeting Rooms","E","S","Sort and check overlap · 10 cos."],
[359,"Logger Rate Limiter","E","S","Hashmap of last timestamp · 22 cos."],
[362,"Design Hit Counter","M","S","Queue / circular buffer · 24 cos."],
[373,"Find K Pairs with Smallest Sums","M","S","Min-heap frontier · 10 cos."],
[1642,"Furthest Building You Can Reach","M","S","Min-heap of largest jumps · 12 cos."],
[1146,"Snapshot Array","M","S","Per-index (version,value) + bisect · 17 cos."],
[1166,"Design File System","M","S","Hashmap / trie of paths · 11 cos."],
[588,"Design In-Memory File System","H","X","Trie of dirs · 15 cos."],
[642,"Design Search Autocomplete System","H","X","Trie + top-3 ranking · 13 cos."],
[432,"All O`one Data Structure","H","X","Doubly-linked buckets · 13 cos."]
]},
{"t":"Backtracking","w":"Week 8","c":"Choose-explore-unchoose, pruning, duplicate handling","q":[
[78,"Subsets","M","M","Include / exclude decision tree · 21 cos."],
[90,"Subsets II","M","S","Sort + skip duplicates at same level"],
[46,"Permutations","M","M","Used[] array / swap · 25 cos."],
[47,"Permutations II","M","S","Sort + skip duplicates"],
[39,"Combination Sum","M","M","Reuse same index, prune on target · 26 cos."],
[40,"Combination Sum II","M","M","Sort + skip duplicates, no reuse · 15 cos."],
[77,"Combinations","M","S","Choose k from n, start index"],
[17,"Letter Combinations of a Phone Number","M","M","Digit-by-digit recursion · 37 cos."],
[22,"Generate Parentheses","M","M","Track open/close counts · 35 cos."],
[79,"Word Search","M","M","Grid DFS + visited · 36 cos."],
[131,"Palindrome Partitioning","M","S","Partition + palindrome check · 11 cos."],
[51,"N-Queens","H","S","Column / diagonal sets · 16 cos."],
[216,"Combination Sum III","M","S","Pick k numbers to sum n"],
[93,"Restore IP Addresses","M","S","4 segments with validation · 19 cos."],
[89,"Gray Code","M","S","Reflect-and-prefix / bit trick"],
[401,"Binary Watch","E","S","Count bits combos"],
[784,"Letter Case Permutation","M","S","Branch on letters"],
[967,"Numbers With Same Consecutive Differences","M","S","Digit DFS"],
[1079,"Letter Tile Possibilities","M","S","Count with duplicates"],
[526,"Beautiful Arrangement","M","S","Permutation with pruning"],
[491,"Non-decreasing Subsequences","M","S","Subsets with dedupe per level"],
[473,"Matchsticks to Square","M","X","Bucket filling DFS"],
[698,"Partition to K Equal Sum Subsets","M","X","Bucket DFS + pruning"],
[140,"Word Break II","H","X","DFS + memo · 17 cos."],
[282,"Expression Add Operators","H","X","Track last operand"],
[301,"Remove Invalid Parentheses","H","X","BFS / DFS min removals"],
[1239,"Maximum Length of a Concatenated String with Unique Characters","M","S","Bitmask subsets"],
[2044,"Count Number of Maximum Bitwise-OR Subsets","M","S","Subset enumeration"],
[37,"Sudoku Solver","H","X","Backtrack with row/col/box sets · 17 cos."]
]},
{"t":"Graphs","w":"Week 9","c":"Grid BFS/DFS, topological sort, Dijkstra, Union-Find, MST","q":[
[200,"Number of Islands","M","M","Grid DFS/BFS flood fill · 81 cos."],
[695,"Max Area of Island","M","M","Grid DFS returning area · 18 cos."],
[733,"Flood Fill","E","S","Basic grid DFS · 13 cos."],
[133,"Clone Graph","M","M","DFS/BFS + hashmap old->new · 18 cos."],
[417,"Pacific Atlantic Water Flow","M","S","Reverse multi-source DFS from oceans · 12 cos."],
[130,"Surrounded Regions","M","S","Mark border-connected 'O's · 12 cos."],
[994,"Rotting Oranges","M","M","Multi-source BFS · 52 cos."],
[542,"01 Matrix","M","S","Multi-source BFS from zeros · 11 cos."],
[207,"Course Schedule","M","M","Cycle detection / Kahn's topological sort · 44 cos."],
[210,"Course Schedule II","M","M","Topological ordering · 35 cos."],
[547,"Number of Provinces","M","M","DFS or Union-Find components"],
[684,"Redundant Connection","M","S","Union-Find cycle detection"],
[785,"Is Graph Bipartite?","M","S","BFS/DFS 2-colouring · 10 cos."],
[127,"Word Ladder","H","M","BFS on implicit graph · 38 cos."],
[743,"Network Delay Time","M","M","Dijkstra"],
[787,"Cheapest Flights Within K Stops","M","S","Bellman-Ford / BFS with stops · 18 cos."],
[1584,"Min Cost to Connect All Points","M","S","MST (Prim's / Kruskal's) · 10 cos."],
[1971,"Find if Path Exists in Graph","E","S","DFS / Union-Find basics"],
[399,"Evaluate Division","M","S","Weighted graph DFS · 22 cos."],
[1631,"Path With Minimum Effort","M","S","Dijkstra on grid"],
[841,"Keys and Rooms","M","S","DFS reachability"],
[797,"All Paths From Source to Target","M","S","DFS backtracking on DAG"],
[1091,"Shortest Path in Binary Matrix","M","S","BFS on grid with 8 directions · 14 cos."],
[1926,"Nearest Exit from Entrance in Maze","M","S","BFS on grid"],
[329,"Longest Increasing Path in a Matrix","H","S","DFS + memo · 18 cos."],
[463,"Island Perimeter","E","S","Count land edges"],
[1020,"Number of Enclaves","M","S","Border DFS"],
[310,"Minimum Height Trees","M","S","Leaf-peeling topological"],
[802,"Find Eventual Safe States","M","S","Reverse topo / cycle colour"],
[886,"Possible Bipartition","M","S","Bipartite check · 10 cos."],
[990,"Satisfiability of Equality Equations","M","S","Union-Find"],
[721,"Accounts Merge","M","S","Union-Find on emails · 16 cos."],
[1319,"Number of Operations to Make Network Connected","M","S","Components - 1 · 10 cos."],
[1466,"Reorder Routes to Make All Paths Lead to the City Zero","M","S","DFS with direction"],
[778,"Swim in Rising Water","H","S","Dijkstra / BS + BFS"],
[1514,"Path with Maximum Probability","M","S","Dijkstra max-heap"],
[1334,"Find the City With the Smallest Number of Neighbors at a Threshold Distance","M","S","Floyd-Warshall"],
[269,"Alien Dictionary","H","M","Build graph from word pairs + topo sort · 18 cos."],
[261,"Graph Valid Tree","M","S","n-1 edges + connected"],
[323,"Number of Connected Components in an Undirected Graph","M","S","DSU / DFS"],
[332,"Reconstruct Itinerary","H","X","Hierholzer's Eulerian path · 22 cos."],
[752,"Open the Lock","M","S","BFS on states · 15 cos."],
[286,"Walls and Gates","M","S","Multi-source BFS · 10 cos."],
[934,"Shortest Bridge","M","S","DFS island then BFS · 17 cos."],
[815,"Bus Routes","H","S","BFS over routes · 17 cos."],
[505,"The Maze","M","S","Rolling DFS/Dijkstra · 13 cos."]
]},
{"t":"Dynamic Programming","w":"Week 10-11","c":"State + recurrence, knapsack types, LIS/LCS, grid and stock DP","q":[
[70,"Climbing Stairs","E","M","dp[i] = dp[i-1] + dp[i-2] · 35 cos."],
[746,"Min Cost Climbing Stairs","E","S","Min of last two steps"],
[198,"House Robber","M","M","Take-or-skip recurrence · 36 cos."],
[213,"House Robber II","M","M","Run House Robber on two ranges (circular) · 17 cos."],
[91,"Decode Ways","M","M","Count ways, one-digit vs two-digit · 19 cos."],
[322,"Coin Change","M","M","Unbounded knapsack, min coins · 38 cos."],
[518,"Coin Change II","M","S","Unbounded knapsack, count combinations · 11 cos."],
[152,"Maximum Product Subarray","M","M","Track both max and min product · 22 cos."],
[139,"Word Break","M","M","dp[i] = any word ends at i · 27 cos."],
[300,"Longest Increasing Subsequence","M","M","O(n^2) DP, then O(n log n) patience sort · 28 cos."],
[416,"Partition Equal Subset Sum","M","M","0/1 knapsack, subset sum · 13 cos."],
[279,"Perfect Squares","M","S","Coin-change style DP · 12 cos."],
[62,"Unique Paths","M","M","Grid DP · 20 cos."],
[63,"Unique Paths II","M","S","Grid DP with obstacles · 11 cos."],
[64,"Minimum Path Sum","M","S","Grid DP min cost · 15 cos."],
[120,"Triangle","M","S","Bottom-up DP · 10 cos."],
[931,"Minimum Falling Path Sum","M","S","Grid DP with 3 neighbours"],
[1143,"Longest Common Subsequence","M","M","Classic 2D string DP · 18 cos."],
[516,"Longest Palindromic Subsequence","M","S","LCS with reversed string · 12 cos."],
[72,"Edit Distance","M","M","Insert / delete / replace DP · 23 cos."],
[494,"Target Sum","M","S","Subset-sum transform or memo"],
[221,"Maximal Square","M","S","dp = min of 3 neighbours + 1 · 27 cos."],
[309,"Best Time to Buy and Sell Stock with Cooldown","M","S","State machine DP"],
[115,"Distinct Subsequences","H","X","2D DP counting matches · 10 cos."],
[740,"Delete and Earn","M","S","House Robber on values · 13 cos."],
[377,"Combination Sum IV","M","S","Ordered ways DP"],
[343,"Integer Break","M","S","DP / math split into 3s"],
[673,"Number of Longest Increasing Subsequence","M","S","LIS with counts"],
[354,"Russian Doll Envelopes","H","X","Sort + LIS · 13 cos."],
[96,"Unique Binary Search Trees","M","S","Catalan DP"],
[474,"Ones and Zeroes","M","S","2D knapsack"],
[983,"Minimum Cost For Tickets","M","S","Day-based DP · 12 cos."],
[714,"Best Time to Buy and Sell Stock with Transaction Fee","M","S","Hold/sold states"],
[123,"Best Time to Buy and Sell Stock III","H","S","k=2 state DP · 14 cos."],
[188,"Best Time to Buy and Sell Stock IV","H","X","k-transaction DP · 13 cos."],
[97,"Interleaving String","M","S","2D DP on prefixes"],
[1312,"Minimum Insertion Steps to Make a String Palindrome","H","S","n - LPS"],
[718,"Maximum Length of Repeated Subarray","M","S","Longest common substring DP"],
[1277,"Count Square Submatrices with All Ones","M","S","Maximal square variant"],
[264,"Ugly Number II","M","S","Three-pointer DP"],
[312,"Burst Balloons","H","X","Interval DP, last balloon · 16 cos."],
[1235,"Maximum Profit in Job Scheduling","H","S","Sort + binary search + dp · 22 cos."],
[678,"Valid Parenthesis String","M","S","Track low/high open count · 15 cos."],
[1048,"Longest String Chain","M","S","Sort by length + hashmap dp · 15 cos."],
[132,"Palindrome Partitioning II","H","X","Palindrome table + cut dp"],
[174,"Dungeon Game","H","X","Reverse grid DP · 10 cos."],
[403,"Frog Jump","H","X","Set of jump sizes per stone · 12 cos."],
[1326,"Minimum Number of Taps to Open to Water a Garden","H","X","Jump-game style greedy · 13 cos."],
[741,"Cherry Pickup","H","X","Two walkers simultaneously · 11 cos."],
[1105,"Filling Bookcase Shelves","M","S","1D DP over books"]
]},
{"t":"Greedy, Intervals & Sorting","w":"Week 12","c":"Sort + local choice, exchange argument, interval merge/sweep, comparators","q":[
[455,"Assign Cookies","E","S","Sort both, match smallest first"],
[122,"Best Time to Buy and Sell Stock II","M","S","Sum every positive difference · 29 cos."],
[55,"Jump Game","M","M","Track farthest reachable index · 33 cos."],
[45,"Jump Game II","M","M","BFS-like greedy by ranges · 25 cos."],
[134,"Gas Station","M","M","Running tank; reset start on negative · 27 cos."],
[763,"Partition Labels","M","S","Last occurrence of each char"],
[860,"Lemonade Change","E","S","Greedy change with 5s and 10s"],
[846,"Hand of Straights","M","S","Sorted counter / min-heap"],
[135,"Candy","H","S","Two passes left->right, right->left · 22 cos."],
[56,"Merge Intervals","M","M","Sort by start, merge overlaps · 101 cos."],
[57,"Insert Interval","M","M","Three-phase linear scan · 16 cos."],
[435,"Non-overlapping Intervals","M","M","Sort by end, keep earliest finish · 18 cos."],
[452,"Minimum Number of Arrows to Burst Balloons","M","S","Sort by end, greedy"],
[986,"Interval List Intersections","M","S","Two pointers over sorted lists · 12 cos."],
[1094,"Car Pooling","M","S","Difference array / sweep (free alternative to Meeting Rooms II) · 12 cos."],
[605,"Can Place Flowers","E","S","Greedy scan · 15 cos."],
[1005,"Maximize Sum Of Array After K Negations","E","S","Flip smallest"],
[406,"Queue Reconstruction by Height","M","S","Sort + insert at index"],
[912,"Sort an Array","M","M","Merge sort / heap sort · 10 cos."],
[179,"Largest Number","M","M","Custom comparator · 19 cos."],
[274,"H-Index","M","S","Sort / counting"],
[1122,"Relative Sort Array","E","S","Counting sort with order"],
[1288,"Remove Covered Intervals","M","S","Sort by start, end desc"],
[228,"Summary Ranges","E","S","Group consecutive"],
[2406,"Divide Intervals Into Minimum Number of Groups","M","S","Sweep line / heap"],
[1353,"Maximum Number of Events That Can Be Attended","M","S","Sort + min-heap of end days · 15 cos."],
[759,"Employee Free Time","H","X","Merge all intervals, find gaps · 12 cos."],
[1229,"Meeting Scheduler","M","S","Two pointers on sorted slots · 10 cos."]
]},
{"t":"Matrix, Math & Bit Manipulation","w":"Week 12","c":"In-place matrix ops, boundaries, fast power, XOR tricks, n&(n-1)","q":[
[48,"Rotate Image","M","M","Transpose + reverse rows · 34 cos."],
[54,"Spiral Matrix","M","M","Four shrinking boundaries · 49 cos."],
[73,"Set Matrix Zeroes","M","S","Use first row/col as markers · 20 cos."],
[50,"Pow(x, n)","M","M","Fast exponentiation · 21 cos."],
[204,"Count Primes","M","S","Sieve of Eratosthenes · 15 cos."],
[9,"Palindrome Number","E","S","Reverse half the number · 30 cos."],
[7,"Reverse Integer","M","S","Overflow-safe digit pop/push · 19 cos."],
[66,"Plus One","E","S","Carry handling · 13 cos."],
[202,"Happy Number","E","S","Cycle detection / set · 24 cos."],
[13,"Roman to Integer","E","M","Subtract if smaller precedes larger · 36 cos."],
[136,"Single Number","E","M","XOR cancels pairs · 15 cos."],
[191,"Number of 1 Bits","E","M","n & (n-1) trick · 11 cos."],
[338,"Counting Bits","E","S","dp[i] = dp[i>>1] + (i&1)"],
[268,"Missing Number","E","S","XOR or sum formula · 17 cos."],
[190,"Reverse Bits","E","S","Shift and build result · 10 cos."],
[371,"Sum of Two Integers","M","S","XOR for sum, AND<<1 for carry"],
[231,"Power of Two","E","S","n & (n-1) == 0 · 10 cos."],
[289,"Game of Life","M","S","In-place state encoding · 13 cos."],
[498,"Diagonal Traverse","M","S","Direction flip · 12 cos."],
[59,"Spiral Matrix II","M","S","Boundary fill · 11 cos."],
[566,"Reshape the Matrix","E","S","Flatten index math"],
[867,"Transpose Matrix","E","S","Swap i,j"],
[766,"Toeplitz Matrix","E","S","Compare diagonals"],
[172,"Factorial Trailing Zeroes","M","S","Count factors of 5"],
[258,"Add Digits","E","S","Digital root"],
[263,"Ugly Number","E","S","Divide by 2,3,5"],
[326,"Power of Three","E","S","Loop / max power"],
[412,"Fizz Buzz","E","S","Modulo checks · 17 cos."],
[461,"Hamming Distance","E","S","XOR + popcount"],
[405,"Convert a Number to Hexadecimal","E","S","4-bit grouping"],
[201,"Bitwise AND of Numbers Range","M","S","Common prefix bits"],
[137,"Single Number II","M","S","Count bits mod 3"],
[260,"Single Number III","M","S","XOR + split by set bit"],
[166,"Fraction to Recurring Decimal","M","S","Long division + remainder map · 10 cos."],
[29,"Divide Two Integers","M","S","Bit-shift subtraction"],
[149,"Max Points on a Line","H","X","Slope hashmap with gcd · 16 cos."],
[1706,"Where Will the Ball Fall","M","S","Simulate column by column"]
]},
{"t":"Union-Find & Advanced Structures","w":"Week 13","c":"DSU, segment tree / BIT and divide-and-conquer favourites","q":[
[947,"Most Stones Removed with Same Row or Column","M","S","DSU on rows/cols · 10 cos."],
[1202,"Smallest String With Swaps","M","S","DSU groups + sort"],
[305,"Number of Islands II","H","X","Online DSU"],
[307,"Range Sum Query - Mutable","M","S","Fenwick / segment tree"],
[315,"Count of Smaller Numbers After Self","H","X","Merge sort or BIT"],
[493,"Reverse Pairs","H","X","Merge-sort counting"],
[218,"The Skyline Problem","H","X","Sweep line + heap · 12 cos."]
]}
];
